name: Build and save my Docker image to Exoscale registry

on:
  push:
    branches:
      - main  # Déclenchement lorsque le code est poussé sur main
    paths:
      - "src/backend/**"
env:
  REG_NAME: "exo.container-registry.com" # Nom du registre Exoscale sans "exo.container-registry.com"
  IMAGE_NAME: "backend-app" # Nom de votre image Docker

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Exoscale Container Registry
        run: |
          docker login -u quentin.badoud@edufr.ch -p ${{ secrets.TOKEN_DOCKER_LOGIN }} exo.container-registry.com

      - name: Build docker image
        run: |
          docker build -t exo.container-registry.com/testLeon:latest .

      - name: Tag image
        run: |
          docker tag  exo.container-registry.com/c213-emf/testLeon:latest

      - name: Push docker image to Exoscale registry
        run: |
          docker push exo.container-registry.com/c213-emf/testLeon:latest
          
